const PAGE_WIDTH = 841.89;
const PAGE_HEIGHT = 595.28;
const MARGIN_X = 28;
const HEADER_HEIGHT = 76;
const FOOTER_HEIGHT = 28;
const TABLE_HEADER_HEIGHT = 18;
const ROW_HEIGHT = 16;
const FONT_SIZE = 6.4;
const HEADER_FONT_SIZE = 6.5;

function ascii(value) {
  return String(value ?? "")
    .normalize("NFKD")
    .replace(/[^\x20-\x7E]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function pdfEscape(value) {
  return ascii(value)
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)");
}

function textWidthEstimate(text, fontSize = FONT_SIZE) {
  return ascii(text).length * fontSize * 0.5;
}

function truncateToWidth(value, width, fontSize = FONT_SIZE) {
  const raw = ascii(value);
  const usable = Math.max(4, width - 6);
  if (textWidthEstimate(raw, fontSize) <= usable) return raw;

  const suffix = "...";
  const suffixWidth = textWidthEstimate(suffix, fontSize);
  const maxChars = Math.max(1, Math.floor((usable - suffixWidth) / (fontSize * 0.5)));
  return `${raw.slice(0, maxChars)}${suffix}`;
}

function calculateColumnWidths(columns, rows, tableWidth) {
  const weights = columns.map((column) => {
    const samples = [column.label, ...rows.slice(0, 100).map((row) => row[column.key])];
    const maxLength = Math.max(...samples.map((sample) => ascii(sample).length), 4);
    return Math.min(22, Math.max(6, maxLength));
  });

  const minWidth = columns.length >= 10 ? 42 : 54;
  const initial = weights.map((weight) => Math.max(minWidth, weight * 4.7));
  const total = initial.reduce((sum, width) => sum + width, 0);

  if (total <= tableWidth) {
    const extra = (tableWidth - total) / columns.length;
    return initial.map((width) => width + extra);
  }

  const scale = tableWidth / total;
  return initial.map((width) => width * scale);
}

function drawText(commands, text, x, y, options = {}) {
  const {
    size = FONT_SIZE,
    bold = false,
  } = options;
  commands.push("BT");
  commands.push(`/${bold ? "F2" : "F1"} ${size.toFixed(2)} Tf`);
  commands.push(`${x.toFixed(2)} ${y.toFixed(2)} Td`);
  commands.push(`(${pdfEscape(text)}) Tj`);
  commands.push("ET");
}

function drawLine(commands, x1, y1, x2, y2, width = 0.35) {
  commands.push(`${width.toFixed(2)} w`);
  commands.push(`${x1.toFixed(2)} ${y1.toFixed(2)} m ${x2.toFixed(2)} ${y2.toFixed(2)} l S`);
}

function drawHeader(commands, title, generatedAt, generatedBy, pageNo) {
  drawText(commands, "BrewSmart", MARGIN_X, PAGE_HEIGHT - 30, { size: 17, bold: true });
  drawText(commands, "AI-Based Smart Tea Warehouse Management & Optimization System", MARGIN_X, PAGE_HEIGHT - 45, { size: 7.2 });
  drawText(commands, title, MARGIN_X, PAGE_HEIGHT - 65, { size: 11.5, bold: true });

  const rightX = PAGE_WIDTH - MARGIN_X - 205;
  drawText(commands, `Generated: ${generatedAt}`, rightX, PAGE_HEIGHT - 31, { size: 7 });
  drawText(commands, `Generated by: ${generatedBy || "BrewSmart User"}`, rightX, PAGE_HEIGHT - 44, { size: 7 });
  drawText(commands, `Page: ${pageNo}`, rightX, PAGE_HEIGHT - 57, { size: 7 });

  drawLine(commands, MARGIN_X, PAGE_HEIGHT - 73, PAGE_WIDTH - MARGIN_X, PAGE_HEIGHT - 73, 0.7);
}

function drawFooter(commands, rowCount) {
  const y = 20;
  drawLine(commands, MARGIN_X, y + 9, PAGE_WIDTH - MARGIN_X, y + 9, 0.35);
  drawText(commands, `BrewSmart Report | Records: ${rowCount}`, MARGIN_X, y, { size: 6.6 });
  drawText(commands, "Generated from live BrewSmart report data", PAGE_WIDTH - MARGIN_X - 205, y, { size: 6.6 });
}

function buildPages({ title, columns, rows, generatedBy }) {
  const tableWidth = PAGE_WIDTH - MARGIN_X * 2;
  const widths = calculateColumnWidths(columns, rows, tableWidth);
  const pages = [];
  const generatedAt = new Date().toLocaleString();

  const rowsPerPage = Math.max(
    1,
    Math.floor((PAGE_HEIGHT - HEADER_HEIGHT - FOOTER_HEIGHT - TABLE_HEADER_HEIGHT - 20) / ROW_HEIGHT)
  );

  const pageCount = Math.max(1, Math.ceil(rows.length / rowsPerPage));

  for (let pageIndex = 0; pageIndex < pageCount; pageIndex += 1) {
    const commands = [];
    drawHeader(commands, title, generatedAt, generatedBy, pageIndex + 1);

    let yTop = PAGE_HEIGHT - HEADER_HEIGHT - 8;
    let x = MARGIN_X;

    commands.push("0.94 g");
    commands.push(`${MARGIN_X.toFixed(2)} ${(yTop - TABLE_HEADER_HEIGHT).toFixed(2)} ${tableWidth.toFixed(2)} ${TABLE_HEADER_HEIGHT.toFixed(2)} re f`);
    commands.push("0 g");

    columns.forEach((column, index) => {
      const width = widths[index];
      drawText(
        commands,
        truncateToWidth(column.label, width, HEADER_FONT_SIZE),
        x + 3,
        yTop - 12,
        { size: HEADER_FONT_SIZE, bold: true }
      );
      drawLine(commands, x, yTop, x, yTop - TABLE_HEADER_HEIGHT, 0.35);
      x += width;
    });
    drawLine(commands, x, yTop, x, yTop - TABLE_HEADER_HEIGHT, 0.35);
    drawLine(commands, MARGIN_X, yTop, PAGE_WIDTH - MARGIN_X, yTop, 0.55);
    drawLine(commands, MARGIN_X, yTop - TABLE_HEADER_HEIGHT, PAGE_WIDTH - MARGIN_X, yTop - TABLE_HEADER_HEIGHT, 0.55);

    let currentY = yTop - TABLE_HEADER_HEIGHT;
    const start = pageIndex * rowsPerPage;
    const pageRows = rows.slice(start, start + rowsPerPage);

    if (pageRows.length === 0) {
      drawText(commands, "No data available for this report.", MARGIN_X + 4, currentY - 18, { size: 8.5 });
    }

    pageRows.forEach((row) => {
      x = MARGIN_X;
      columns.forEach((column, index) => {
        const width = widths[index];
        drawText(
          commands,
          truncateToWidth(row[column.key], width),
          x + 3,
          currentY - 11,
          { size: FONT_SIZE }
        );
        drawLine(commands, x, currentY, x, currentY - ROW_HEIGHT, 0.25);
        x += width;
      });
      drawLine(commands, x, currentY, x, currentY - ROW_HEIGHT, 0.25);
      drawLine(commands, MARGIN_X, currentY - ROW_HEIGHT, PAGE_WIDTH - MARGIN_X, currentY - ROW_HEIGHT, 0.25);
      currentY -= ROW_HEIGHT;
    });

    drawFooter(commands, rows.length);
    pages.push(commands.join("\n"));
  }

  return pages;
}

function buildPdfString({ title, columns, rows, generatedBy }) {
  const pages = buildPages({ title, columns, rows, generatedBy });
  const objects = [];

  // 1: Catalog, 2: Pages tree, 3/4: fonts. Page/content objects follow.
  objects[1] = "<< /Type /Catalog /Pages 2 0 R >>";
  objects[3] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>";
  objects[4] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>";

  const kids = [];
  pages.forEach((stream, index) => {
    const pageObj = 5 + index * 2;
    const contentObj = pageObj + 1;
    kids.push(`${pageObj} 0 R`);

    const streamLength = new TextEncoder().encode(stream).length;
    objects[contentObj] = `<< /Length ${streamLength} >>\nstream\n${stream}\nendstream`;
    objects[pageObj] =
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH.toFixed(2)} ${PAGE_HEIGHT.toFixed(2)}] ` +
      `/Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${contentObj} 0 R >>`;
  });

  objects[2] = `<< /Type /Pages /Kids [${kids.join(" ")}] /Count ${pages.length} >>`;

  let pdf = "%PDF-1.4\n%BrewSmart\n";
  const offsets = [0];
  const encoder = new TextEncoder();

  for (let i = 1; i < objects.length; i += 1) {
    offsets[i] = encoder.encode(pdf).length;
    pdf += `${i} 0 obj\n${objects[i]}\nendobj\n`;
  }

  const xrefOffset = encoder.encode(pdf).length;
  pdf += `xref\n0 ${objects.length}\n`;
  pdf += "0000000000 65535 f \n";
  for (let i = 1; i < objects.length; i += 1) {
    pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return pdf;
}

export function buildReportPdf({ title, columns, rows, generatedBy = "" }) {
  if (!title || !Array.isArray(columns) || columns.length === 0 || !Array.isArray(rows)) {
    throw new Error("Invalid report data for PDF generation.");
  }

  return buildPdfString({ title, columns, rows, generatedBy });
}

export function downloadReportPdf({ title, columns, rows, generatedBy = "" }) {
  const pdf = buildReportPdf({ title, columns, rows, generatedBy });
  const blob = new Blob([pdf], { type: "application/pdf" });
  const safeTitle = ascii(title).replace(/[^A-Za-z0-9_-]+/g, "_").replace(/^_+|_+$/g, "");
  const date = new Date().toISOString().slice(0, 10);
  const filename = `${safeTitle || "BrewSmart_Report"}_${date}.pdf`;

  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
